#!/bin/bash
# daily-strategy.sh — once-per-day GHP strategy brief generated by Claude.
#
# Reads recent operational state (engagement log, last posts + insights,
# untapped-warm count from latest sweep, current post queue) and asks
# `claude -p` for the top 3 highest-leverage actions for the next 24h plus
# any content angles to push to the content engine.
#
# Output: pi/strategy/YYYY-MM-DD.md committed to main + ntfy ping.
# Cadence: 1x/day (14:00 UTC ~ 10:00 ET, human morning window) per
# feedback_ghp_human_pattern.md. NOT a check+act loop — read-only briefing.

set -u

# gh token via pass (same pattern as self-review.sh)
if command -v pass >/dev/null 2>&1; then
  GH_TOKEN=$(pass show ghp/github_token 2>/dev/null) || true
  export GH_TOKEN
fi

REPO_DIR="${GHP_REPO_DIR:-$HOME/golden-home-project}"
ENV_FILE="${ENV_FILE:-$HOME/claude-skill/config/env}"
DATE=$(date -u +%Y-%m-%d)
STRATEGY_REL="pi/strategy"
OUT_REL="$STRATEGY_REL/$DATE.md"

cd "$REPO_DIR" || { echo "FATAL: cannot cd to $REPO_DIR" >&2; exit 1; }
mkdir -p "$STRATEGY_REL"

# Work from fresh main.
git fetch --quiet origin main
git checkout --quiet main
git reset --hard --quiet origin/main

# --- Source 1: last 24h engagement actions ---------------------------------
ENG_LOG="social/engagement_log.json"
ENG_RECENT="(no engagement log)"
if [ -s "$ENG_LOG" ]; then
  ENG_RECENT=$(python3 - <<'PY' 2>/dev/null || echo "(parse failed)"
import json, datetime as dt
try:
    data = json.load(open("social/engagement_log.json"))
except Exception:
    print("(empty)"); raise SystemExit
# Real schema: {"_doc":..., "summary":..., "actions":[{timestamp, action, target, ...}, ...]}
actions = data.get("actions", []) if isinstance(data, dict) else (data if isinstance(data, list) else [])
cutoff = dt.datetime.utcnow() - dt.timedelta(hours=36)
recent = []
for a in actions:
    ts = a.get("timestamp", "")
    try:
        t = dt.datetime.fromisoformat(ts.replace("Z",""))
    except Exception:
        continue
    if t >= cutoff:
        recent.append(f"  {ts}  {a.get('action','?')}  {a.get('target','')}  {a.get('reason','')}")
print("\n".join(recent[-80:]) or "(none in window)")
PY
)
fi

# Untapped-warm count from latest sweep
UNTAPPED=$(python3 - <<'PY' 2>/dev/null || echo "?"
import json
try:
    data = json.load(open("social/engagement_log.json"))
except Exception:
    print("?"); raise SystemExit
actions = data.get("actions", []) if isinstance(data, dict) else (data if isinstance(data, list) else [])
# Most-recent inbox_sweep wins
for a in reversed(actions):
    if a.get("action") == "inbox_sweep":
        uw = a.get("untapped_warm", a.get("untapped", []))
        if isinstance(uw, list):
            print(len(uw)); raise SystemExit
        if isinstance(uw, int):
            print(uw); raise SystemExit
print(0)
PY
)

# --- Source 2: last 3 posts + insights -------------------------------------
RECENT_POSTS=$(python3 - <<'PY' 2>/dev/null || echo "(no archive)"
import json, glob, os
try:
    arr = json.load(open("social/posted_archive.json"))
except Exception:
    print("(empty)"); raise SystemExit
posts = arr[-5:] if isinstance(arr, list) else []
# Load latest insights file
ins_files = sorted(glob.glob("automation/logs/ig_insights_*.json"))
insights = {}
if ins_files:
    try:
        latest = json.load(open(ins_files[-1]))
        # try multiple shapes
        if isinstance(latest, list):
            for row in latest:
                mid = str(row.get("id") or row.get("media_id") or "")
                if mid: insights[mid] = row
        elif isinstance(latest, dict):
            for k, v in latest.items():
                insights[str(k)] = v
    except Exception:
        pass
for p in posts:
    mid = str(p.get("media_id",""))
    cap = (p.get("caption","") or "").replace("\n"," ")[:120]
    ins = insights.get(mid, {})
    likes = ins.get("like_count") or ins.get("likes") or "?"
    comments = ins.get("comments_count") or ins.get("comments") or "?"
    reach = ins.get("reach") or "?"
    print(f"  media={mid}  likes={likes}  comments={comments}  reach={reach}")
    print(f"    cap: {cap}")
PY
)

# --- Source 3: post queue size + next 3 captions ---------------------------
QUEUE_HEAD=$(python3 - <<'PY' 2>/dev/null || echo "(no queue)"
import json
try:
    q = json.load(open("social/post_queue.json"))
except Exception:
    print("(empty)"); raise SystemExit
items = q if isinstance(q, list) else q.get("items", [])
print(f"queue_size={len(items)}")
for it in items[:3]:
    cap = (it.get("caption","") or "").replace("\n"," ")[:120]
    print(f"  - {cap}")
PY
)

# --- Source 4: prior strategy brief (newest, to avoid repeats) -------------
PREV_BRIEF="(none)"
last_brief=$(ls -1 "$STRATEGY_REL"/*.md 2>/dev/null | grep -v "$DATE" | tail -1 || true)
if [ -n "$last_brief" ] && [ -f "$last_brief" ]; then
  PREV_BRIEF=$(tail -n 80 "$last_brief")
fi

# --- Prompt Claude ----------------------------------------------------------
PROMPT=$(cat <<EOF
You are the GHP daily strategy reviewer. The Pi already runs IG engagement
sweeps 2x/day, GitHub Actions posts content on schedule, and the watchdog
catches infra rot. Your job is to read the last 24-36 hours of operational
state below and decide the 3 HIGHEST-LEVERAGE human-judgment actions for
the next 24 hours.

Hard constraints (from GHP CEO memory + feedback rules):
- Subscription + free tools only.
- Revenue first. Skip cosmetic ideas.
- Never propose increasing engagement-sweep cadence above 1-2x/day.
- Never propose paid SaaS or new API tokens.
- Skip ._community / promo accounts in any outreach.
- Engagement caps per day: 10 follow / 30 like / 5 comment. Do not exceed.

Output format (markdown):
## Top 3 actions for next 24h
For each action: WHAT, WHO/WHERE (handles, file paths, post IDs), WHY (signal from data below), and HOW (one-line concrete step).

## Content angle to push
ONE concrete content angle the content-engine should pick up next, based on what's working (or what's missing) in recent posts. Reference real numbers.

## Watch-outs
ONE-line list of things that look off in the data and need eyes.

If the data shows the week was clean and nothing actionable, say so plainly.

=== Last 24-36h engagement actions ===
$ENG_RECENT

=== Untapped warm prospects (people who engaged us but we have not reciprocated) ===
count=$UNTAPPED

=== Last 5 posts + their insights ===
$RECENT_POSTS

=== Post queue head ===
$QUEUE_HEAD

=== Yesterday's strategy brief (do not repeat verbatim) ===
$PREV_BRIEF
EOF
)

REPORT=$(echo "$PROMPT" | /usr/bin/claude -p --model claude-opus-4-7 2>&1 \
  || echo "claude CLI failed: $?")

cat > "$OUT_REL" <<EOF
# GHP daily strategy brief — $DATE

Generated by \`pi/strategy/daily-strategy.sh\` on $(hostname) at $(date -u -Iseconds).

**Inputs:** engagement log (last 36h), untapped_warm count, last 5 posts + insights, post queue head, prior brief.

$REPORT
EOF

# --- Commit to main + push --------------------------------------------------
git add "$OUT_REL"
LINES=$(wc -l < "$OUT_REL" | tr -d ' ')

git -c user.name="GHP Strategy Bot" \
    -c user.email="goldenhomeprojectllc@gmail.com" \
    commit -m "Strategy brief: $DATE ($LINES lines)" >/dev/null 2>&1 || true

git push --quiet origin main || true

# --- ntfy ping --------------------------------------------------------------
if [ -r "$ENV_FILE" ]; then
  TOPIC=$(grep '^NTFY_TOPIC=' "$ENV_FILE" | cut -d= -f2- | tr -d "'\"")
  if [ -n "${TOPIC:-}" ]; then
    curl -sf -m 10 \
      -H "Title: GHP daily strategy brief ready" \
      -H "Tags: brain,ghp" \
      -d "Brief: $OUT_REL (untapped_warm=$UNTAPPED)" \
      "https://ntfy.sh/$TOPIC" >/dev/null || true
  fi
fi

echo "wrote $OUT_REL"
